config/routes.rb
Flickr::Application.routes.draw do
 resources :password_resets

  get "login" => "sessions#new", :as => "login"
  get "logout" => "sessions#destroy", :as => "logout"
  get "signup" => "users#new", :as => "signup"

  get "users/new"

  resources :albums do
    resources :photos
  end
  resources :users do
    member do
      get :activate
    end
  end
  resources :sessions
   root :to => 'albums#index'

end

app/models/album.rb
class Album < ActiveRecord::Base
  attr_accessible :name

  has_many :photos
  belongs_to :user
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  attr_accessible :album_id, :url

  belongs_to :album

  mount_uploader :url, ImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  attr_accessible :email, :password, :password_confirmation

  validates_confirmation_of :password
  # validates_uniqueness_of :email
  has_many :albums
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  # GET /albums
  # GET /albums.json
  def index
    @albums = Album.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @albums }
    end
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
    @album = Album.find(params[:id])
    @photos = @album.photos
    @photo = Photo.create(params[:photo])
    @album.photos << @photo
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @album }
    end
  end

  # GET /albums/new
  # GET /albums/new.json
  def new
    @album = Album.new
    @photo = @album.photos.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @album }
    end
  end

  # GET /albums/1/edit
  def edit
    @album = Album.find(params[:id])
    @photo = @album.photos.find(params[:id])
  end

  # POST /albums
  # POST /albums.json
  def create
    @album = Album.new(params[:album])
    @photo = @album.photos.create(params[:photo])

    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: 'Album was successfully created.' }
        format.json { render json: @album, status: :created, location: @album }
      else
        format.html { render action: "new" }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /albums/1
  # PUT /albums/1.json
  def update
    @album = Album.find(params[:id])
    @photo = @album.photos.find(params[:id])

    respond_to do |format|
      if @album.update_attributes(params[:album])
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @album = Album.find(params[:id])
    @photo = @album.photos.find(params[:id])
    @album.destroy

    respond_to do |format|
      format.html { redirect_to albums_url }
      format.json { head :no_content }
    end
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
    def require_login
      unless logged_in?
        flash[:error] = "You must be logged in to view this page"
        redirect_to new_login_url
      end
    end

    def current_user
      if session[:user_id]
        @current_user = User.find(session[:user_id])
      else
        @current_user = nil
      end
    end
  helper_method :current_user
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def create
    @user = User.find_by_email(params[:email])
    @user.deliver_reset_password_instructions! if @user
    redirect_to(root_path, :notice => "Instructions to reset your password have been sent to your email")
  end

  def edit
    @user = User.load_from_reset_password_token(params[:id])
    @token = params[:id]
    not_authenticated unless @user
  end

  def update
    @token =params[:token]
    @user = User.load_from_reset_password_token(params[:token])
    not_authenticated and return unless @user
    @user.password_confirmation = params[:user][:password_confirmation]
    if @user.change_password!(params[:user][:password])
      redirect_to(root_path, :notice => "Password successfully updated!")
    else
      render :action => "edit"
    end
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  # GET /photos
  # GET /photos.json
  def index
    @album = Album.find(params[:album_id])
    @photos = @album.photos.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @photos }
    end
  end

  # GET /photos/new
  # GET /photos/new.json
  def new
    @album = Album.find(params[:album_id])
    @photo = @album.photos.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @photo }
    end
  end

  # GET /photos/1/edit
  def edit
    @album = Album.find(params[:album_id])
    @photo = @album.photos.find(params[:id])
  end

  # POST /photos
  # POST /photos.json
  def create
    @album = Album.find(params[:album_id])
    @photo = @album.photos.new(params[:photo])

    respond_to do |format|
      if @photo.save!
        format.html { redirect_to @photo.album, notice: 'Photo was successfully created.' }
        format.json { render json: @photo, status: :created, location: @photo }
      else
        format.html { render action: "new" }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /photos/1
  # PUT /photos/1.json
  def update
    @album = Album.find(params[:album_id])
    @photo = @album.photos.find(params[:id])

    respond_to do |format|
      if @photo.update_attributes(params[:photo])
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end
  # GET /photos/1
  # GET /photos/1.json
  def show
    @photo = Photo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @photo }
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @album = Album.find(params[:album_id])
    @photo = @album.photos.find(params[:id])
    @photo.destroy

    respond_to do |format|
      format.html { redirect_to photos_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = login(params[:email], params[:password], params[:remember_me])
    if user
      redirect_back_or_to root_url, :notice => "Logged in!"
    else
      flash.now.alert = "Email or password invalid"
      render :new
    end
  end

  def destroy
    logout
    redirect_to root_url, :notice => "Logged out."
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      #send email
      UserMailer.activation_needed_email(@user).deliver
      redirect_to root_url, :notice => "Sign up sucessful!"
    else
      render :new
    end
  end

    def activate
      if(@user = User.load_from_activation_token(params[:id]))
        @user.activate!
        redirect_to(login_path, :notice => 'User was sucessfully activated!')
      else
        not_authenticated
      end
    end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/_form.html.haml
= form_for @album do |f|
  - if @album.errors.any?
    #error_explanation
      %h2= "#{pluralize(@album.errors.count, "error")} prohibited this album from being saved:"
      %ul
        - @album.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/albums/edit.html.haml
%h1 Editing album

= render 'form'

= link_to 'Show', @album
\|
= link_to 'Back', albums_path

app/views/albums/index.html.haml
%h1 Listing albums

%table
  %tr
    %th Name
    %th
    %th
    %th

  - @albums.each do |album|
    %tr
      %td= album.name
      %td= link_to 'Show', album
      %td= link_to 'Edit', edit_album_path(album)
      %td= link_to 'Destroy', album, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Album', new_album_path

app/views/albums/new.html.haml
%h1 New album

= render 'form'

= link_to 'Back', albums_path

app/views/albums/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @album.name
  = link_to 'New Photo', new_album_photo_path(@album)

  %p
  -@album.photos.each do |photo|
    = image_tag photo.url

= link_to 'Edit', edit_album_path(@album)
\|
= link_to 'Back', albums_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flickr</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="container">
  <div class="user_nav">
    <% if current_user %>
      Logged in as <%= current_user.email %>
      <%= link_to "Log Out", logout_path %>
    <% else %>
      <%= link_to "Sign up", signup_path %>
      <%= link_to "Log in", login_path %>
    <% end %>
  </div>
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    <% end %>
</div>

<%= yield %>

</body>
</html>

app/views/password_resets/create.html.haml
%h1 PasswordResets#create
%p Find me in app/views/password_resets/create.html.haml

app/views/password_resets/edit.html.haml
%h1 Choose a new password
= form_for @user, :url => password_reset_path(@user), :html => {:method => :put} do |f|
  - if @user.errors.any?
    #error_explanation
      %h2
        = pluralize(@user.errors.count, "error")
        prohibited this user from being saved:
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :email
    %br/
    = @user.email
  .field
    = f.label :password
    %br/
    = f.password_field :password
  .field
    = f.label :password_confirmation
    %br/
    = f.password_field :password_confirmation
    = hidden_field_tag :token, @token
  .actions
    = f.submit

app/views/password_resets/update.html.haml
%h1 PasswordResets#update
%p Find me in app/views/password_resets/update.html.haml

app/views/photos/_form.html.haml
= form_for([@album, @photo], :html_options => {:multipart => true}) do |f|
  - if @photo.errors.any?
    #error_explanation
      %h2= "#{pluralize(@photo.errors.count, "error")} prohibited this photo from being saved:"
      %ul
        - @photo.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :url
    = f.file_field :url
  .actions
    = f.submit 'Save'

app/views/photos/edit.html.haml
%h1 Editing photo

= render 'form'

= link_to 'Show', @photo
\|
= link_to 'Back', album_photos_path(@album)

app/views/photos/index.html.haml
%h1 Listing photos

%table
  %tr
    %th Url
    %th Album
    %th
    %th
    %th

  - @photos.each do |photo|
    %tr
      %td= photo.url
      %td= photo.album_id
      %td= link_to 'Show', album_photo_path(@album, photo)
      %td= link_to 'Edit', edit_album_photo_path(@album, photo)
      %td= link_to 'Destroy', [@album, photo],:method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Photo', new_album_photo_path(@album)

app/views/photos/new.html.haml
%h1 New photo

= render 'form'

= link_to 'Back', album_photos_path(@album)

app/views/photos/show.html.haml
%p#notice= notice

%p
  %b Url:
  = @photo.url
%p
  %b Album:
  = @photo.album_id

= link_to 'Edit', edit_album_photo_path(@album, photo)
\|
= link_to 'Back', album_photos_path

app/views/users/_form.html.haml
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  %div.large-4.columns
    %label Email
    =f.text_field :email

  %div.large-4.columns
    %label Password
    =f.password_field :password

  %div.large-4.columns
    %label Confirm
    =f.password_field :password_confirmation

  .actions
    = f.submit 'Sign Up'

app/views/users/new.html.haml
%h1 User#new
%p Find me in app/views/user/new.html.haml
= render 'form'

= link_to 'Back', users_path